name: 'build'
on: [ 'pull_request', 'push' ]
jobs:
    build:
        if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
        runs-on: 'ubuntu-latest'
        env:
            ORG_GRADLE_PROJECT_ZeruxLibsUsername: '${{ secrets.ZERUX_LIBS_USER }}'
            ORG_GRADLE_PROJECT_ZeruxLibsPassword: '${{ secrets.ZERUX_LIBS_PASSWORD }}'
        steps:
            -   name: 'checkout repo'
                uses: 'actions/checkout@v2'
            -   name: 'setup JDK'
                uses: 'actions/setup-java@v1'
                with:
                    java-version: 8
            -   name: 'build'
                run: './gradlew build'
#            -   name: 'publish'
#                if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
#                run: './gradlew publish'
#                env:
#                    ZERUX_CI_USER: '${{ secrets.ZERUX_CI_USER }}'
#                    ZERUX_CI_PASSWORD: '${{ secrets.ZERUX_CI_PASSWORD }}'